---
title: "Modeling Data-Level Spatial Dependence in Multivariate Generalized Extreme Value Distributions with Copulas Based on Gaussian Markov Random Fields"
author: 
  name: Brynjólfur Gauti Guðrúnar Jónsson
  affiliation: University of Iceland
  email: brynjolfur@hi.is
  url: bggj.is
format: 
  pdf: default
  docx: default
---

When working with spatially distributed extreme values, we can relatively easily add spatial dependence to the parameters governing each location's Generalized Extreme Value (GEV) distribution (nearby locations have similar parameter values), but we also need to model the dependence in the observed data itself (i.e. extreme events tend to happen at similar times in nearby locations). By using copulas based on Gaussian Markov random fields (GMRF) we might be able to more accurately represent the data-level dependence while aiming to keep the computation-time feasible.

In this talk, I will present my PhD research on incorporating data-level spatial dependence in the GEV distribution for improved modeling of extreme precipitation in large datasets. The talk will cover how to include spatial dependence in GEV parameters using the Besag-York-Mollié model before moving on to the modeling of data-level dependence with GMRF copulas. The talk ends with results from a simulation study showing how this might be feasible in a spatial process with GEV margins and data-level dependence described by a GMRF copula.
